spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:65.0.77.91}:${MYSQL_PORT:3306}/${MYSQL_DB:userservice}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
server.port=9898

##jwt.secret=bXlTZWNyZXRLZXlGb3JKV1QxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=

logging.level.org.springframework.security=DEBUG
logging.level.your.package.name=DEBUG


##Kafka Producer Configuration
spring.kafka.bootstrap-servers=65.0.77.91:9092
spring.kafka.topic-json.name=user_service
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springBoot.serializer.UserInfoSerializer
spring.kafka.consumer.properties.spring.json.type.mapping=auth:com.springBoot.model.UserInfoDto
